### ISSUE TITLE
Covariates are read-only in warped_stepwise

### ISSUE THREAD

**Issue by nfusi** [PMBio/warpedLMM#2]
Some people have reported that warped_stepwise crashes when doing more than 1 iteration:

Traceback (most recent call last):
  File "C:\Users\Antonio\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Antonio\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Antonio\Anaconda\lib\site-packages\warpedlmm\__main__.py", line 53, in <module>
    pv_cutoff=options.pv_cutoff)
  File "C:\Users\Antonio\Anaconda\lib\site-packages\warpedlmm\stepwise.py", line 46, in warped_stepwise
    covariates -= covariates.mean(0)
ValueError: output array is read-only

**Comment by nfusi** [comment]
Fixed in e8c11b
