### ISSUE TITLE
_tkinter.TclError: couldn't connect to display "localhost:12.0"

### ISSUE THREAD

**Issue by unclesho** [PMBio/warpedLMM#3]
trace:
std=.1.000000 has illegal value for SNPs[:][44]
Two or more individuals have the same phenotype value. If the data is censored, an appropriate censorship model is needed before the data is passed to WarpedLMM.
Optimization restart 1/3, f: -103.9284
Optimization restart 2/3, f: -103.2122
Optimization restart 3/3, f: -103.9237
WARNING:root:NaN beta value seen, may be due to an SNC (a constant SNP)
Iteration: 1, significant SNPs: 51, included SNPs: 0,  heritability: 0.4054, f: 103.928415209
Two or more individuals have the same phenotype value. If the data is censored, an appropriate censorship model is needed before the data is passed to WarpedLMM.
Optimization restart 1/3, f: -103.2131
Optimization restart 2/3, f: -108.4375
Optimization restart 3/3, f: -137.6876
WARNING:root:NaN beta value seen, may be due to an SNC (a constant SNP)
Iteration: 2, significant SNPs: 0, included SNPs: 1,  heritability: 1.0000, f: 137.687583974
WARNING:root:NaN beta value seen, may be due to an SNC (a constant SNP)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/warpedlmm/__main__.py", line 82, in <module>
    m.plot_warping()
  File "/usr/local/lib/python2.7/site-packages/warpedlmm/warpedlmm.py", line 209, in plot_warping
    self.warping_function.plot(self.warping_params, self.Y_untransformed.min(), self.Y_untransformed.max())
  File "/usr/local/lib/python2.7/site-packages/warpedlmm/util/warping_functions.py", line 37, in plot
    plt.figure()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/local/lib/python2.7/lib-tk/Tkinter.py", line 1745, in **init**
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:12.0"

**Comment by unclesho** [comment]
Request for additional features:
1. Switch to turn on/off plotting
2. Switch to turn on/off genotype-phenotype association

Thanks!

**Comment by bhosaleshivam** [comment]
Traceback (most recent call last):
  File "FINAL.py", line 943, in <module>
    train()
  File "FINAL.py", line 906, in train
    save_img([mos, frame, base, fake, raw], ['Input', 'Frame', 'base', 'SR', 'Ground Truth'], epoch)
  File "FINAL.py", line 934, in save_img
    plt.savefig(path)
  File "/home/17id92r01/conda/ls/envs/py3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 688, in savefig
    fig = gcf()
  File "/home/17id92r01/conda/ls/envs/py3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/home/17id92r01/conda/ls/envs/py3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 525, in figure
    **kwargs)
  File "/home/17id92r01/conda/ls/envs/py3/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 3218, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/17id92r01/conda/ls/envs/py3/lib/python3.5/site-packages/matplotlib/backends/_backend_tk.py", line 1008, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/17id92r01/conda/ls/envs/py3/lib/python3.5/tkinter/__init__.py", line 1876, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:12.0"
